// Code generated by protoc-gen-go.
// source: gameMsg.proto
// DO NOT EDIT!

/*
Package protof is a generated protocol buffer package.

It is generated from these files:
	gameMsg.proto

It has these top-level messages:
	Message1
*/
package protof

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message1_ID int32

const (
	Message1_PIND            Message1_ID = 100
	Message1_CS_LOGINMESSAGE Message1_ID = 101
	Message1_SC_LOGINMESSAGE Message1_ID = 102
)

var Message1_ID_name = map[int32]string{
	100: "PIND",
	101: "CS_LOGINMESSAGE",
	102: "SC_LOGINMESSAGE",
}
var Message1_ID_value = map[string]int32{
	"PIND":            100,
	"CS_LOGINMESSAGE": 101,
	"SC_LOGINMESSAGE": 102,
}

func (x Message1_ID) Enum() *Message1_ID {
	p := new(Message1_ID)
	*p = x
	return p
}
func (x Message1_ID) String() string {
	return proto.EnumName(Message1_ID_name, int32(x))
}
func (x *Message1_ID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message1_ID_value, data, "Message1_ID")
	if err != nil {
		return err
	}
	*x = Message1_ID(value)
	return nil
}
func (Message1_ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message1 struct {
	Ping             *Message1_Ping            `protobuf:"bytes,100,opt,name=ping" json:"ping,omitempty"`
	CsLoginMessage   *Message1_CS_LoginMessage `protobuf:"bytes,101,opt,name=cs_login_message" json:"cs_login_message,omitempty"`
	ScLoginMessage   *Message1_SC_LoginMessage `protobuf:"bytes,102,opt,name=sc_login_message" json:"sc_login_message,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Message1) Reset()                    { *m = Message1{} }
func (m *Message1) String() string            { return proto.CompactTextString(m) }
func (*Message1) ProtoMessage()               {}
func (*Message1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message1) GetPing() *Message1_Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *Message1) GetCsLoginMessage() *Message1_CS_LoginMessage {
	if m != nil {
		return m.CsLoginMessage
	}
	return nil
}

func (m *Message1) GetScLoginMessage() *Message1_SC_LoginMessage {
	if m != nil {
		return m.ScLoginMessage
	}
	return nil
}

type Message1_Ping struct {
	Time             *float32 `protobuf:"fixed32,1,req,name=time" json:"time,omitempty"`
	SerTime          *int32   `protobuf:"varint,2,opt,name=serTime" json:"serTime,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Message1_Ping) Reset()                    { *m = Message1_Ping{} }
func (m *Message1_Ping) String() string            { return proto.CompactTextString(m) }
func (*Message1_Ping) ProtoMessage()               {}
func (*Message1_Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Message1_Ping) GetTime() float32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Message1_Ping) GetSerTime() int32 {
	if m != nil && m.SerTime != nil {
		return *m.SerTime
	}
	return 0
}

type Message1_CS_LoginMessage struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Opt              *int32  `protobuf:"varint,3,req,name=opt" json:"opt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message1_CS_LoginMessage) Reset()                    { *m = Message1_CS_LoginMessage{} }
func (m *Message1_CS_LoginMessage) String() string            { return proto.CompactTextString(m) }
func (*Message1_CS_LoginMessage) ProtoMessage()               {}
func (*Message1_CS_LoginMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Message1_CS_LoginMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Message1_CS_LoginMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Message1_CS_LoginMessage) GetOpt() int32 {
	if m != nil && m.Opt != nil {
		return *m.Opt
	}
	return 0
}

type Message1_SC_LoginMessage struct {
	Code             *int32  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	LoginTime        *int32  `protobuf:"varint,3,req,name=loginTime" json:"loginTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message1_SC_LoginMessage) Reset()                    { *m = Message1_SC_LoginMessage{} }
func (m *Message1_SC_LoginMessage) String() string            { return proto.CompactTextString(m) }
func (*Message1_SC_LoginMessage) ProtoMessage()               {}
func (*Message1_SC_LoginMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Message1_SC_LoginMessage) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Message1_SC_LoginMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Message1_SC_LoginMessage) GetLoginTime() int32 {
	if m != nil && m.LoginTime != nil {
		return *m.LoginTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Message1)(nil), "protof.Message1")
	proto.RegisterType((*Message1_Ping)(nil), "protof.Message1.Ping")
	proto.RegisterType((*Message1_CS_LoginMessage)(nil), "protof.Message1.CS_LoginMessage")
	proto.RegisterType((*Message1_SC_LoginMessage)(nil), "protof.Message1.SC_LoginMessage")
	proto.RegisterEnum("protof.Message1_ID", Message1_ID_name, Message1_ID_value)
}

func init() { proto.RegisterFile("gameMsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x8f, 0x41, 0x4b, 0x84, 0x40,
	0x18, 0x86, 0x71, 0x74, 0x6b, 0xf7, 0xdb, 0x42, 0x9b, 0x08, 0xc4, 0x93, 0x6c, 0x04, 0x9e, 0x84,
	0x3a, 0x2d, 0x9d, 0x8a, 0xdd, 0x65, 0x11, 0x72, 0x5b, 0xb0, 0xbb, 0x88, 0x8e, 0xc3, 0x40, 0x3a,
	0xe2, 0xf8, 0x13, 0xfa, 0xe1, 0xf1, 0x7d, 0x16, 0x94, 0xb5, 0xa7, 0x81, 0xf7, 0x7d, 0x9f, 0x79,
	0x66, 0xe0, 0x52, 0x16, 0x8d, 0x48, 0x8d, 0x8c, 0xbb, 0x5e, 0x0f, 0x9a, 0x9f, 0xd1, 0x51, 0xaf,
	0x3e, 0x6c, 0x98, 0xa7, 0xc2, 0x98, 0x42, 0x8a, 0x7b, 0x7e, 0x0b, 0x4e, 0xa7, 0x5a, 0xe9, 0x57,
	0xa1, 0x15, 0x2d, 0x1f, 0x6e, 0xc6, 0x69, 0x1d, 0x7f, 0xf7, 0xf1, 0x51, 0xb5, 0x92, 0x3f, 0x82,
	0x57, 0x9a, 0xfc, 0x5d, 0x4b, 0xd5, 0xe6, 0xcd, 0xd8, 0xf8, 0x82, 0x80, 0xf0, 0x0f, 0xb0, 0xc9,
	0xf2, 0x17, 0x1c, 0x7e, 0x05, 0xc8, 0x9a, 0x72, 0xc2, 0xd6, 0x27, 0xd8, 0x6c, 0xf3, 0x8b, 0x0d,
	0xee, 0xc0, 0x21, 0xff, 0x05, 0x38, 0x83, 0x6a, 0x84, 0x6f, 0x85, 0x2c, 0x62, 0xdc, 0x85, 0x73,
	0x23, 0xfa, 0x37, 0x0c, 0x58, 0x68, 0x45, 0xb3, 0x60, 0x0d, 0xee, 0xd4, 0x0a, 0xc0, 0x54, 0x45,
	0xfb, 0x19, 0xd2, 0x6d, 0x41, 0x63, 0x16, 0x2d, 0xf8, 0x12, 0x6c, 0xdd, 0x0d, 0xbe, 0x8d, 0x55,
	0xf0, 0x04, 0xee, 0xc4, 0x89, 0xeb, 0x52, 0x57, 0xe2, 0x5f, 0xf6, 0x0a, 0x16, 0xf4, 0x11, 0x72,
	0xd3, 0x0d, 0xab, 0x35, 0xb0, 0x64, 0xcb, 0xe7, 0xe0, 0x1c, 0x93, 0xc3, 0xd6, 0xab, 0xf8, 0xf5,
	0xf8, 0x96, 0xd7, 0x7d, 0x72, 0x48, 0x77, 0x59, 0xf6, 0xbc, 0xdf, 0x79, 0x02, 0x43, 0xd4, 0xfc,
	0x0c, 0xeb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xe9, 0xd2, 0x5a, 0x9e, 0x01, 0x00, 0x00,
}
