// Code generated by protoc-gen-go.
// source: gameMsg.proto
// DO NOT EDIT!

/*
Package protof is a generated protocol buffer package.

It is generated from these files:
	gameMsg.proto

It has these top-level messages:
	Message1
*/
package protof

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message1_ID int32

const (
	Message1_PIND            Message1_ID = 100
	Message1_CS_LOGINMESSAGE Message1_ID = 101
	Message1_SC_LOGINMESSAGE Message1_ID = 102
	Message1_CS_FIGHTDATA    Message1_ID = 103
	Message1_SC_FIGHTDATA    Message1_ID = 104
	Message1_CS_FIGHTSTART   Message1_ID = 105
	Message1_SC_FIGHTSTART   Message1_ID = 106
	Message1_CS_GETRANK      Message1_ID = 107
	Message1_SC_GETRANK      Message1_ID = 108
)

var Message1_ID_name = map[int32]string{
	100: "PIND",
	101: "CS_LOGINMESSAGE",
	102: "SC_LOGINMESSAGE",
	103: "CS_FIGHTDATA",
	104: "SC_FIGHTDATA",
	105: "CS_FIGHTSTART",
	106: "SC_FIGHTSTART",
	107: "CS_GETRANK",
	108: "SC_GETRANK",
}
var Message1_ID_value = map[string]int32{
	"PIND":            100,
	"CS_LOGINMESSAGE": 101,
	"SC_LOGINMESSAGE": 102,
	"CS_FIGHTDATA":    103,
	"SC_FIGHTDATA":    104,
	"CS_FIGHTSTART":   105,
	"SC_FIGHTSTART":   106,
	"CS_GETRANK":      107,
	"SC_GETRANK":      108,
}

func (x Message1_ID) Enum() *Message1_ID {
	p := new(Message1_ID)
	*p = x
	return p
}
func (x Message1_ID) String() string {
	return proto.EnumName(Message1_ID_name, int32(x))
}
func (x *Message1_ID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message1_ID_value, data, "Message1_ID")
	if err != nil {
		return err
	}
	*x = Message1_ID(value)
	return nil
}
func (Message1_ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message1 struct {
	Ping             *Message1_Ping            `protobuf:"bytes,100,opt,name=ping" json:"ping,omitempty"`
	CsLoginMessage   *Message1_CS_LoginMessage `protobuf:"bytes,101,opt,name=cs_login_message" json:"cs_login_message,omitempty"`
	ScLoginMessage   *Message1_SC_LoginMessage `protobuf:"bytes,102,opt,name=sc_login_message" json:"sc_login_message,omitempty"`
	CsFightData      *Message1_CS_FightData    `protobuf:"bytes,103,opt,name=cs_fight_data" json:"cs_fight_data,omitempty"`
	ScFightData      *Message1_SC_FightData    `protobuf:"bytes,104,opt,name=sc_fight_data" json:"sc_fight_data,omitempty"`
	CsFightStart     *Message1_CS_FightStart   `protobuf:"bytes,105,opt,name=cs_fight_start" json:"cs_fight_start,omitempty"`
	ScFightStart     *Message1_SC_FightStart   `protobuf:"bytes,106,opt,name=sc_fight_start" json:"sc_fight_start,omitempty"`
	CsGetRank        *Message1_CS_GetRank      `protobuf:"bytes,107,opt,name=cs_get_rank" json:"cs_get_rank,omitempty"`
	ScGetRank        *Message1_SC_GetRank      `protobuf:"bytes,108,opt,name=sc_get_rank" json:"sc_get_rank,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Message1) Reset()                    { *m = Message1{} }
func (m *Message1) String() string            { return proto.CompactTextString(m) }
func (*Message1) ProtoMessage()               {}
func (*Message1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message1) GetPing() *Message1_Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *Message1) GetCsLoginMessage() *Message1_CS_LoginMessage {
	if m != nil {
		return m.CsLoginMessage
	}
	return nil
}

func (m *Message1) GetScLoginMessage() *Message1_SC_LoginMessage {
	if m != nil {
		return m.ScLoginMessage
	}
	return nil
}

func (m *Message1) GetCsFightData() *Message1_CS_FightData {
	if m != nil {
		return m.CsFightData
	}
	return nil
}

func (m *Message1) GetScFightData() *Message1_SC_FightData {
	if m != nil {
		return m.ScFightData
	}
	return nil
}

func (m *Message1) GetCsFightStart() *Message1_CS_FightStart {
	if m != nil {
		return m.CsFightStart
	}
	return nil
}

func (m *Message1) GetScFightStart() *Message1_SC_FightStart {
	if m != nil {
		return m.ScFightStart
	}
	return nil
}

func (m *Message1) GetCsGetRank() *Message1_CS_GetRank {
	if m != nil {
		return m.CsGetRank
	}
	return nil
}

func (m *Message1) GetScGetRank() *Message1_SC_GetRank {
	if m != nil {
		return m.ScGetRank
	}
	return nil
}

type Message1_Ping struct {
	Time             *float32 `protobuf:"fixed32,1,req,name=time" json:"time,omitempty"`
	SerTime          *int32   `protobuf:"varint,2,opt,name=serTime" json:"serTime,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Message1_Ping) Reset()                    { *m = Message1_Ping{} }
func (m *Message1_Ping) String() string            { return proto.CompactTextString(m) }
func (*Message1_Ping) ProtoMessage()               {}
func (*Message1_Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Message1_Ping) GetTime() float32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Message1_Ping) GetSerTime() int32 {
	if m != nil && m.SerTime != nil {
		return *m.SerTime
	}
	return 0
}

type Message1_CS_LoginMessage struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Opt              *int32  `protobuf:"varint,3,req,name=opt" json:"opt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message1_CS_LoginMessage) Reset()                    { *m = Message1_CS_LoginMessage{} }
func (m *Message1_CS_LoginMessage) String() string            { return proto.CompactTextString(m) }
func (*Message1_CS_LoginMessage) ProtoMessage()               {}
func (*Message1_CS_LoginMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Message1_CS_LoginMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Message1_CS_LoginMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Message1_CS_LoginMessage) GetOpt() int32 {
	if m != nil && m.Opt != nil {
		return *m.Opt
	}
	return 0
}

type Message1_SC_LoginMessage struct {
	Code             *int32  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	LoginTime        *int32  `protobuf:"varint,3,req,name=loginTime" json:"loginTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message1_SC_LoginMessage) Reset()                    { *m = Message1_SC_LoginMessage{} }
func (m *Message1_SC_LoginMessage) String() string            { return proto.CompactTextString(m) }
func (*Message1_SC_LoginMessage) ProtoMessage()               {}
func (*Message1_SC_LoginMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Message1_SC_LoginMessage) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Message1_SC_LoginMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Message1_SC_LoginMessage) GetLoginTime() int32 {
	if m != nil && m.LoginTime != nil {
		return *m.LoginTime
	}
	return 0
}

type Message1_CS_FightData struct {
	Speed            *int32 `protobuf:"varint,1,req,name=speed" json:"speed,omitempty"`
	Attack           *int32 `protobuf:"varint,2,req,name=attack" json:"attack,omitempty"`
	MoveX            *int32 `protobuf:"varint,3,req,name=move_x" json:"move_x,omitempty"`
	MoveY            *int32 `protobuf:"varint,4,req,name=move_y" json:"move_y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Message1_CS_FightData) Reset()                    { *m = Message1_CS_FightData{} }
func (m *Message1_CS_FightData) String() string            { return proto.CompactTextString(m) }
func (*Message1_CS_FightData) ProtoMessage()               {}
func (*Message1_CS_FightData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Message1_CS_FightData) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Message1_CS_FightData) GetAttack() int32 {
	if m != nil && m.Attack != nil {
		return *m.Attack
	}
	return 0
}

func (m *Message1_CS_FightData) GetMoveX() int32 {
	if m != nil && m.MoveX != nil {
		return *m.MoveX
	}
	return 0
}

func (m *Message1_CS_FightData) GetMoveY() int32 {
	if m != nil && m.MoveY != nil {
		return *m.MoveY
	}
	return 0
}

type Message1_SC_FightData struct {
	Round            *int32                   `protobuf:"varint,1,req,name=round" json:"round,omitempty"`
	Result           *int32                   `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	MySide           *Message1_FightStateData `protobuf:"bytes,3,req,name=my_side" json:"my_side,omitempty"`
	OtherSide        *Message1_FightStateData `protobuf:"bytes,4,req,name=other_side" json:"other_side,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *Message1_SC_FightData) Reset()                    { *m = Message1_SC_FightData{} }
func (m *Message1_SC_FightData) String() string            { return proto.CompactTextString(m) }
func (*Message1_SC_FightData) ProtoMessage()               {}
func (*Message1_SC_FightData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *Message1_SC_FightData) GetRound() int32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

func (m *Message1_SC_FightData) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Message1_SC_FightData) GetMySide() *Message1_FightStateData {
	if m != nil {
		return m.MySide
	}
	return nil
}

func (m *Message1_SC_FightData) GetOtherSide() *Message1_FightStateData {
	if m != nil {
		return m.OtherSide
	}
	return nil
}

type Message1_FightStateData struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	MapX             *int32  `protobuf:"varint,2,req,name=map_x" json:"map_x,omitempty"`
	MapY             *int32  `protobuf:"varint,3,req,name=map_y" json:"map_y,omitempty"`
	Life             *int32  `protobuf:"varint,4,req,name=life" json:"life,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message1_FightStateData) Reset()                    { *m = Message1_FightStateData{} }
func (m *Message1_FightStateData) String() string            { return proto.CompactTextString(m) }
func (*Message1_FightStateData) ProtoMessage()               {}
func (*Message1_FightStateData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *Message1_FightStateData) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Message1_FightStateData) GetMapX() int32 {
	if m != nil && m.MapX != nil {
		return *m.MapX
	}
	return 0
}

func (m *Message1_FightStateData) GetMapY() int32 {
	if m != nil && m.MapY != nil {
		return *m.MapY
	}
	return 0
}

func (m *Message1_FightStateData) GetLife() int32 {
	if m != nil && m.Life != nil {
		return *m.Life
	}
	return 0
}

type Message1_CS_FightStart struct {
	Isstart          *bool  `protobuf:"varint,1,req,name=isstart" json:"isstart,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Message1_CS_FightStart) Reset()                    { *m = Message1_CS_FightStart{} }
func (m *Message1_CS_FightStart) String() string            { return proto.CompactTextString(m) }
func (*Message1_CS_FightStart) ProtoMessage()               {}
func (*Message1_CS_FightStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 6} }

func (m *Message1_CS_FightStart) GetIsstart() bool {
	if m != nil && m.Isstart != nil {
		return *m.Isstart
	}
	return false
}

type Message1_SC_FightStart struct {
	IsstartA         *bool  `protobuf:"varint,1,req,name=isstartA" json:"isstartA,omitempty"`
	IsstartB         *bool  `protobuf:"varint,2,req,name=isstartB" json:"isstartB,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Message1_SC_FightStart) Reset()                    { *m = Message1_SC_FightStart{} }
func (m *Message1_SC_FightStart) String() string            { return proto.CompactTextString(m) }
func (*Message1_SC_FightStart) ProtoMessage()               {}
func (*Message1_SC_FightStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 7} }

func (m *Message1_SC_FightStart) GetIsstartA() bool {
	if m != nil && m.IsstartA != nil {
		return *m.IsstartA
	}
	return false
}

func (m *Message1_SC_FightStart) GetIsstartB() bool {
	if m != nil && m.IsstartB != nil {
		return *m.IsstartB
	}
	return false
}

type Message1_CS_GetRank struct {
	Code             *int32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Message1_CS_GetRank) Reset()                    { *m = Message1_CS_GetRank{} }
func (m *Message1_CS_GetRank) String() string            { return proto.CompactTextString(m) }
func (*Message1_CS_GetRank) ProtoMessage()               {}
func (*Message1_CS_GetRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 8} }

func (m *Message1_CS_GetRank) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

type Message1_SC_GetRank struct {
	Code             *int32               `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	RankData         []*Message1_RankData `protobuf:"bytes,2,rep,name=rank_data" json:"rank_data,omitempty"`
	MyRanking        *Message1_RankData   `protobuf:"bytes,3,req,name=my_ranking" json:"my_ranking,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Message1_SC_GetRank) Reset()                    { *m = Message1_SC_GetRank{} }
func (m *Message1_SC_GetRank) String() string            { return proto.CompactTextString(m) }
func (*Message1_SC_GetRank) ProtoMessage()               {}
func (*Message1_SC_GetRank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 9} }

func (m *Message1_SC_GetRank) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Message1_SC_GetRank) GetRankData() []*Message1_RankData {
	if m != nil {
		return m.RankData
	}
	return nil
}

func (m *Message1_SC_GetRank) GetMyRanking() *Message1_RankData {
	if m != nil {
		return m.MyRanking
	}
	return nil
}

// 排行榜信息
type Message1_RankData struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Score            *int32  `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
	Ranking          *int32  `protobuf:"varint,3,opt,name=ranking" json:"ranking,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message1_RankData) Reset()                    { *m = Message1_RankData{} }
func (m *Message1_RankData) String() string            { return proto.CompactTextString(m) }
func (*Message1_RankData) ProtoMessage()               {}
func (*Message1_RankData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 10} }

func (m *Message1_RankData) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Message1_RankData) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *Message1_RankData) GetRanking() int32 {
	if m != nil && m.Ranking != nil {
		return *m.Ranking
	}
	return 0
}

func init() {
	proto.RegisterType((*Message1)(nil), "protof.Message1")
	proto.RegisterType((*Message1_Ping)(nil), "protof.Message1.Ping")
	proto.RegisterType((*Message1_CS_LoginMessage)(nil), "protof.Message1.CS_LoginMessage")
	proto.RegisterType((*Message1_SC_LoginMessage)(nil), "protof.Message1.SC_LoginMessage")
	proto.RegisterType((*Message1_CS_FightData)(nil), "protof.Message1.CS_FightData")
	proto.RegisterType((*Message1_SC_FightData)(nil), "protof.Message1.SC_FightData")
	proto.RegisterType((*Message1_FightStateData)(nil), "protof.Message1.FightStateData")
	proto.RegisterType((*Message1_CS_FightStart)(nil), "protof.Message1.CS_FightStart")
	proto.RegisterType((*Message1_SC_FightStart)(nil), "protof.Message1.SC_FightStart")
	proto.RegisterType((*Message1_CS_GetRank)(nil), "protof.Message1.CS_GetRank")
	proto.RegisterType((*Message1_SC_GetRank)(nil), "protof.Message1.SC_GetRank")
	proto.RegisterType((*Message1_RankData)(nil), "protof.Message1.RankData")
	proto.RegisterEnum("protof.Message1_ID", Message1_ID_name, Message1_ID_value)
}

func init() { proto.RegisterFile("gameMsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x94, 0x61, 0x6f, 0x93, 0x40,
	0x18, 0xc7, 0x03, 0xa3, 0x6b, 0xf7, 0xb4, 0xb4, 0x0c, 0x63, 0x82, 0x18, 0xb5, 0x99, 0x31, 0xe1,
	0x85, 0x2e, 0x73, 0x33, 0x66, 0xf1, 0x95, 0xd8, 0xce, 0x5a, 0xb5, 0x73, 0x19, 0xbc, 0x27, 0x17,
	0x38, 0x28, 0x6b, 0x81, 0x86, 0xbb, 0xe9, 0xfa, 0x09, 0xfc, 0x02, 0x7e, 0x02, 0x3f, 0xa9, 0xb9,
	0x3b, 0xe8, 0xa0, 0x1d, 0x89, 0xaf, 0x96, 0x7b, 0xee, 0xff, 0x7b, 0x1e, 0xee, 0xff, 0xfc, 0x57,
	0x50, 0x23, 0x94, 0xe0, 0x19, 0x89, 0x8e, 0x57, 0x79, 0x46, 0x33, 0x7d, 0x9f, 0xff, 0x09, 0x8f,
	0x7e, 0x77, 0xa1, 0x33, 0xc3, 0x84, 0xa0, 0x08, 0xbf, 0xd5, 0x5f, 0x82, 0xb2, 0x8a, 0xd3, 0xc8,
	0x08, 0x86, 0x92, 0xd5, 0x3d, 0x7d, 0x2c, 0xa4, 0xe1, 0x71, 0x79, 0x7f, 0x7c, 0x15, 0xa7, 0x91,
	0xfe, 0x01, 0x34, 0x9f, 0x78, 0xcb, 0x2c, 0x8a, 0x53, 0x2f, 0x11, 0x37, 0x06, 0xe6, 0xc0, 0x70,
	0x07, 0x18, 0x39, 0xde, 0x77, 0x26, 0x2c, 0x0a, 0x8c, 0x25, 0xfe, 0x16, 0x1b, 0x36, 0xb0, 0xce,
	0xa8, 0xce, 0xbe, 0x03, 0xd5, 0x27, 0x5e, 0x18, 0x47, 0x73, 0xea, 0x05, 0x88, 0x22, 0x23, 0xe2,
	0xe0, 0xb3, 0x87, 0x86, 0x7e, 0x66, 0xaa, 0x31, 0xa2, 0x88, 0x51, 0xc4, 0xaf, 0x52, 0xf3, 0x06,
	0xca, 0x19, 0x55, 0xa8, 0xf7, 0xd0, 0xdf, 0xcc, 0x22, 0x14, 0xe5, 0xd4, 0x88, 0x39, 0xf6, 0xbc,
	0x71, 0x98, 0xc3, 0x54, 0x8c, 0xdb, 0x4c, 0x13, 0xdc, 0x4d, 0x03, 0x57, 0x8e, 0x13, 0xdc, 0x09,
	0x74, 0x7d, 0xe2, 0x45, 0x98, 0x7a, 0x39, 0x4a, 0x17, 0xc6, 0x82, 0x43, 0x4f, 0x1f, 0x1a, 0x36,
	0xc1, 0xf4, 0x1a, 0xa5, 0x0b, 0x46, 0x10, 0xff, 0x9e, 0x58, 0x36, 0x10, 0xce, 0xa8, 0x24, 0xcc,
	0x57, 0xa0, 0xf0, 0xfd, 0xf5, 0x40, 0xa1, 0x71, 0x82, 0x0d, 0x69, 0x28, 0x5b, 0xb2, 0x3e, 0x80,
	0x36, 0xc1, 0xb9, 0xcb, 0x0a, 0xf2, 0x50, 0xb2, 0x5a, 0xe6, 0x39, 0x0c, 0xb6, 0xb7, 0x06, 0x20,
	0xc7, 0x01, 0xd7, 0xb7, 0x18, 0x9d, 0x22, 0x2e, 0x96, 0xad, 0x03, 0xbd, 0x0b, 0x7b, 0xd9, 0x8a,
	0x1a, 0x7b, 0xec, 0xca, 0xfc, 0x08, 0x83, 0xed, 0x9d, 0xf5, 0x40, 0xf1, 0xb3, 0x00, 0x3f, 0xc8,
	0x1e, 0xc2, 0x01, 0x0f, 0x02, 0x9f, 0x2d, 0x3a, 0xcc, 0xa0, 0x57, 0x5b, 0x9e, 0x0a, 0x2d, 0xb2,
	0xc2, 0xb8, 0x9c, 0xdd, 0x87, 0x7d, 0x44, 0x29, 0xf2, 0x17, 0xbc, 0x03, 0x3f, 0x27, 0xd9, 0x4f,
	0xec, 0xdd, 0x09, 0x7c, 0x73, 0x5e, 0x1b, 0x0a, 0x6f, 0xf7, 0x47, 0x82, 0x5e, 0x6d, 0xad, 0x2a,
	0xb4, 0xf2, 0xec, 0x36, 0xad, 0xf4, 0xcb, 0x31, 0xb9, 0x5d, 0xd2, 0xa2, 0xdf, 0x09, 0xb4, 0x93,
	0xb5, 0x47, 0xe2, 0x40, 0x7c, 0x4f, 0xf7, 0xf4, 0xc5, 0x8e, 0x9f, 0xe5, 0xce, 0x28, 0xe6, 0x0d,
	0xcf, 0x00, 0x32, 0x3a, 0xc7, 0xb9, 0x80, 0x94, 0xff, 0x82, 0xcc, 0xaf, 0xd0, 0xdf, 0x6a, 0x53,
	0x1a, 0x23, 0x71, 0x63, 0x54, 0x68, 0x25, 0x68, 0xe5, 0xdd, 0x15, 0x5f, 0x55, 0x1c, 0xd7, 0xc5,
	0x23, 0x7b, 0xa0, 0x2c, 0xe3, 0x10, 0x17, 0x4f, 0x1c, 0x82, 0x5a, 0x4f, 0xe0, 0x00, 0xda, 0x31,
	0x11, 0xd1, 0x63, 0xdd, 0x3a, 0xe6, 0x19, 0xa8, 0xf5, 0xac, 0x69, 0xd0, 0x29, 0x14, 0xb6, 0x90,
	0x54, 0x2a, 0x9f, 0xf8, 0xcc, 0x8e, 0x69, 0x02, 0x54, 0xb2, 0x56, 0xdb, 0xa2, 0xf9, 0x0b, 0xe0,
	0x3e, 0x55, 0x5b, 0x1b, 0x7e, 0x0d, 0x07, 0x2c, 0x8e, 0xe2, 0x3f, 0x4d, 0x1e, 0xee, 0x59, 0xdd,
	0xd3, 0x27, 0x3b, 0x76, 0x30, 0x8e, 0x3f, 0xfb, 0x0d, 0x40, 0xb2, 0xe6, 0xf9, 0x65, 0x3f, 0x3a,
	0xc2, 0xf2, 0x66, 0xb9, 0x79, 0x0e, 0x9d, 0x0d, 0xba, 0xe3, 0x18, 0xf1, 0xb3, 0x1c, 0x17, 0x8e,
	0x0d, 0xa0, 0x7d, 0xdf, 0x54, 0xb2, 0x5a, 0x47, 0x7f, 0x25, 0x90, 0xa7, 0x63, 0xbd, 0x03, 0xca,
	0xd5, 0xf4, 0x72, 0xac, 0x05, 0xfa, 0x23, 0x11, 0xf2, 0x1f, 0x93, 0xe9, 0xe5, 0xec, 0xc2, 0x71,
	0xec, 0xc9, 0x85, 0x86, 0x59, 0x91, 0xe5, 0xb7, 0x5a, 0x0c, 0x75, 0x4d, 0x44, 0x72, 0x3a, 0xf9,
	0xe2, 0x8e, 0x6d, 0xd7, 0xd6, 0x22, 0x56, 0x61, 0x86, 0x6e, 0x2a, 0x73, 0xfd, 0x50, 0x2c, 0x81,
	0x55, 0x1c, 0xd7, 0xbe, 0x76, 0xb5, 0x98, 0x95, 0x4a, 0x91, 0x28, 0xdd, 0xe8, 0x7d, 0xe1, 0xe9,
	0x85, 0x7b, 0x6d, 0x5f, 0x7e, 0xd3, 0x16, 0xec, 0xcc, 0x7c, 0x2c, 0xce, 0xcb, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x07, 0x3c, 0x03, 0xb9, 0xa1, 0x05, 0x00, 0x00,
}
